# fly.toml app configuration file generated for supermarket-express-be on 2023-08-25T10:42:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "supermarket-express-be"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 3000

[deploy]
  release_command = "npm run db:migrate"
